create table if not exists users (
    id integer generated by default as identity primary key,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    email varchar(200) not null,
    team_name varchar(60) not null,
    password text not null,
    verification_token varchar(200),
    renew_password_token varchar(200),
    is_verified boolean
);

create table if not exists problems (
    id integer generated by default as identity primary key,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    name varchar(60) not null,
    description varchar(60) not null,
    canvas_link varchar(100) not null,
    initial_config_link varchar(100) not null,
    target_link varchar(100) not null
);

create table if not exists submissions (
    id integer generated by default as identity primary key,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    user_id integer not null,
    problem_id integer not null,
    s3_key varchar(100) not null,
    status varchar(60) not null,
    status_changed_at timestamp with time zone,
    error text,
    score integer
);

create table if not exists support_messages (
    id integer generated by default as identity primary key,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    user_id integer not null,
    content text,
    is_answer boolean
);

create table if not exists announcements (
    id integer generated by default as identity primary key,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    content text
);

create table if not exists results (
    id integer generated by default as identity primary key,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    user_id integer not null,
    problem_id integer not null,
    last_submitted_at timestamp with time zone,
    submission_count integer,
    max_score integer
);