database:
  host: minivinci-dev.czpfcl2hnwoi.us-east-1.rds.amazonaws.com
  user: postgres
  password: A2^LHa6!mt&64$m
  name: postgres
  port: 5432

jwt:
  login_secret: interestingsecret
  verification_secret: anotherinterestingsecret
  renew_password_secret: yetanotherinterestingsecret

async:
  eager: true

email:
  ses_region: us-east-1
  from: noreply@robovinci.xyz
  verification_url: http://dev.robovinci.xyz/users/verification/

redis:
  address: 127.0.0.1:6379

s3:
  region: us-east-1
  submissions_bucket_name: minivinci-dev-submissions

logging:
  output_file: logrus.log
  level: debug
